Bug(KnockoutSpa): Router TS issue
TS erroring out (unable to build) due to `crossroads.normalizeFn = crossroads.NORM_AS_OBJECT;` <-- left hand assignment

```
ERROR in ./ClientApp/router.ts
(21,9): error TS2450: Left-hand side of assignment expression cannot be a constant or a read-only property.
```